version: "2"
services:
  app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ".:/go/app"
    command: nodemon --exec go run internal/main.go --signal SIGTERM